# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('slug', models.SlugField(help_text='\u8bf7\u8f93\u5165\u552f\u4e00\u7684\u94fe\u63a5\u540d\uff0c\u53ef\u4ee5\u5305\u542b\u6570\u5b57\uff0c\u82f1\u6587\u5b57\u6bcd\u548c\u4e0b\u5212\u7ebf', unique=True, verbose_name='\u94fe\u63a5\u540d')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='page/%Y/%m/%d/', verbose_name='\u5c01\u9762')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('link', models.URLField(blank=True, null=True, verbose_name='\u5916\u90e8\u94fe\u63a5')),
                ('template', models.CharField(default='default', max_length=50, verbose_name='\u6a21\u677f')),
                ('sort', models.PositiveIntegerField(default=0, help_text='\u6570\u5b57\u8d8a\u5927\u8d8a\u5f80\u524d', verbose_name='\u6392\u5e8f')),
                ('is_show', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.Page', verbose_name='\u7236\u7ea7')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': '\u9875\u9762',
                'verbose_name_plural': '\u9875\u9762',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
